### ISSUE TITLE
simplejson.decoder.JSONDecodeError when ES returns string errors

### ISSUE THREAD

**Issue by Dieterbe** [humangeo/rawes#11]
I was trying to post data and ES was returning "No handler found for uri [/dieterfoobarbaz/post] and method [PUT]"

and rawes would do this:

```
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    es.put('dieterfoobarbaz/post', data=data)
  File "/home/dieter/workspaces/eclipse/anthracite/rawes/rawes/elastic.py", line 47, in put
    return self.request('put', path, **kwargs)
  File "/home/dieter/workspaces/eclipse/anthracite/rawes/rawes/elastic.py", line 75, in request
    return self.connection.request(method, new_path, **kwargs)
  File "/home/dieter/workspaces/eclipse/anthracite/rawes/rawes/http_connection.py", line 43, in request
    return self._decode(response)
  File "/home/dieter/workspaces/eclipse/anthracite/rawes/rawes/http_connection.py", line 49, in _decode
    decoded = json.loads(response.text)
  File "/usr/lib/python2.7/site-packages/simplejson/__init__.py", line 453, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 429, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 451, in raw_decode
    raise JSONDecodeError("No JSON object could be decoded", s, idx)
simplejson.decoder.JSONDecodeError: No JSON object could be decoded: line 1 column 0 (char 0)
```

**Comment by dwnoble** [comment]
Agreed that this is undesired behavior.  Also I support your comment on issue #8 that raising exceptions on HTTP codes >= 400 should be the default - I will incorporate this in the next release in the next day or so.

**Comment by Dieterbe** [comment]
thanks :)

**Comment by dwnoble** [comment]
OK fixed this issue, and also made throwing exceptions on http error codes (>=400) the default behavior.  Removed except_on_error param from the Elastic constructor
